---
title: "Introduction and hypotheses"
---

## Introduction

Trade-offs between reproduction and other traits like survival are central to life history theory. Individuals that invest more in reproduction are expected to have higher reproductive succcess, at the cost of reduced survival. However, the molecular mechanisms that underlie the link between reproductive investment and fitness remain relatively poorly understood. Here, we test whether epigenetic changes can underlie variation in reproductive investment. 

The black grouse faces extreme costs of reproduction during the lekking period, in which they intensively fight to hold territories for several weeks per year. This intensive fighting is not only energy-demanding, but also time-intensive, meaning the birds sacrifice valuable time that could be spent on foraging. Previous research also shows that males with high investment lose the most body mass (@lebigrePhysiologicalCostsEnforce2013a). The black grouse therefore provides an ideal study system to investigate the molecular mechanisms underlying the link between reproductive investment and fitness, as the cost of reproduction is exceptionally high.

## Structure

This repository page is divided in three main sections, following our manuscript:

1. Are there any epigenetic changes that occur during the lekking period?

2. Are epigenetic changes predictive of fitness?

3. Is reproductive investment / cost predictive of epigenetic change?

Additionally, we explore our data and elaborate on some bigger sections by dividing them up in sub-sections.

## Data

Our data comprises epigenetic data (DNA methylation), fitness data (mating success and survival), behaviour (indicators of reproductive investment: lek attendance, fighting rate and lek centrality), morphological changes (change in body mass), physiological changes (change in immunoglobulins, parasites and haematocrit). 51 male black grouse were captured in Central Finland before (Jan - March) and after (April - May) the lekking season. Some birds were captured across multiple years, totalling to 118 captures of black grouse males that allow the assessment of short-term methylation changes.
