project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "The role of epigenetics in regulating life history trade-offs"
  author: "Rebecca S. Chen"
  cover-image: img/grouse.jpeg
  chapters:
      - index.qmd
      - qmd/0_intro_hypothesis.qmd
      - qmd/1_explore.qmd
      - qmd/2_filter.qmd
      - qmd/3_changing_meth.qmd
      - qmd/4_effort_meth.qmd
      - qmd/5_physio_meth.qmd
      - qmd/6_fitness_meth.qmd
#      - qmd/7_annotate.qmd
#      - qmd/8_mutual_sites.qmd
#      - qmd/9_discussion.qmd
  navbar:
    search: true
  favicon: img/grouse_silhouette.png

bibliography: bibliography.bib

format:
  html:
    theme: lux
    toc: true
    

editor: visual

