project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "The role of epigenetics in regulating life history trade-offs"
  author: "Rebecca S. Chen"
  cover-image: img/grouse.jpeg
  chapters:
      - index.qmd
      - qmd/1_intro_hypothesis.qmd
      - qmd/2_wgbs.qmd
      - qmd/3_explore.qmd
      - qmd/4_filter.qmd
      - qmd/5_changing_meth.qmd
      - qmd/6_effort_meth.qmd
      - qmd/7_physio_meth.qmd
      - qmd/8_fitness_meth.qmd
      - qmd/9_mutual_sites.qmd
  navbar:
    search: true
  favicon: img/grouse_silhouette.png

bibliography: bibliography.bib

format:
  html:
    theme: lux
    toc: true
    

editor: visual

