project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "Epigenetic changes associated with reproductive investment in a lekking bird"
  author: "Rebecca S. Chen"
  cover-image: img/grouse.jpeg
  chapters:
      - index.qmd
      - qmd/1_explore.qmd
      - qmd/2_filter.qmd
      - qmd/3_changing_meth.qmd
      - qmd/4_effort_meth.qmd
      - qmd/5_physio_meth.qmd
      - qmd/6_fitness_meth.qmd
  navbar:
    search: true
  favicon: img/grouse_silhouette.png

format:
  html:
    theme: lux
    toc: true
    

editor: visual

